# Generated by Django 5.2.1 on 2025-07-02 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0004_alter_jobseekerskill_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='email',
        ),
    ]
