# Generated by Django 5.2.1 on 2025-06-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0002_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='resume',
            field=models.ImageField(blank=True, upload_to='job_seeker_profile/resume/'),
        ),
    ]
