# Generated by Django 5.2.1 on 2025-06-24 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0003_jobseekerprofile_resume'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobseekerskill',
            unique_together={('job_seeker', 'skill')},
        ),
    ]
