# Generated by Django 5.2.1 on 2025-06-16 18:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerprofile',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='contact_person',
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='email',
            field=models.CharField(default='test@gmail.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='logo',
            field=models.ImageField(default='test_logo', upload_to='company_logos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='name',
            field=models.CharField(default='company', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='number_employees',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000)]),
            preserve_default=False,
        ),
    ]
