# Generated by Django 5.2.1 on 2025-06-20 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeer', '0002_remove_employerprofile_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='logo',
            field=models.ImageField(blank=True, upload_to='company_logos/'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='number_employees',
            field=models.IntegerField(),
        ),
    ]
