# Generated by Django 5.2.1 on 2025-07-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_customuser_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[(1, "Job Seeker"), (2, "Employer")], max_length=20
            ),
        ),
    ]
