# Generated by Django 5.2.1 on 2025-06-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeer', '0003_alter_employerprofile_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
