# Generated by Django 5.2.1 on 2025-06-03 14:40

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_password', models.CharField(max_length=128, verbose_name='password')),
                ('user_last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('user_email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('user_created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_mfa_secret', models.CharField(blank=True, max_length=32, null=True)),
                ('user_mfa_enabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
