# Generated by Django 5.2.1 on 2025-06-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'Job Seeker'), (2, 'Employeer')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
